#pragma once

#define STEP_ENGINE_PLATFORM Windows

#define PLATFORM_STRING_INTERNAL(x) #x
#define PLATFORM_STRING(x) PLATFORM_STRING_INTERNAL(x)
#define PLATFORM_CONCAT_INTERNAL(x, y) x##y
#define PLATFORM_CONCAT(x, y) PLATFORM_CONCAT_INTERNAL(x, y)
#define PLATFORM_HEADER(prefix, name) PLATFORM_STRING(prefix/STEP_ENGINE_PLATFORM/PLATFORM_CONCAT(STEP_ENGINE_PLATFORM, name))
